spring.datasource.url=jdbc:mysql://localhost:3306/industrial_project
spring.datasource.username=root
spring.datasource.password=Bhumika@4545

spring.jpa.hibernate.ddl-auto=update
#INSTRUCTIONS:
# update username or password based on your local DB
# always pull latest code before starting work
#always resolve merge conflicts properly before pushing

